### ISSUE TITLE
Column View not seen for initial few times

### ISSUE THREAD

**Issue by AnujaK** [AnujaK/AnswerReader#5]
When installed and launched for the first time, it either shows blank screen or in case it gets loaded, it does not show column view.  Only after launching the app for a few times, it starts working properly.

**Comment by ranjan-rk** [comment]
started working on it.

**Comment by ranjan-rk** [comment]
Fixed. Version: 0.4.0.2 contains the fix.

**Comment by AnujaK** [comment]
Tested. Works fine. Closing this issue.
